#!/usr/bin/env python
import argparse
import csv
import json
from pathlib import Path


ENCODINGS = ["utf-8-sig", "utf-8", "gb18030", "cp936", "latin-1"]


def requireMatplotlib():
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    plt.rcParams["font.sans-serif"] = ["Microsoft YaHei", "SimHei", "Noto Sans CJK SC", "Arial Unicode MS", "DejaVu Sans"]
    plt.rcParams["axes.unicode_minus"] = False
    return plt


def readCsv(path):
    for encoding in ENCODINGS:
        try:
            text = Path(path).read_text(encoding=encoding)
            rows = list(csv.DictReader(text.splitlines()))
            return rows, encoding
        except UnicodeError:
            continue
    text = Path(path).read_text(encoding="utf-8", errors="replace")
    return list(csv.DictReader(text.splitlines())), "utf-8-replace"


def toFloat(value):
    try:
        text = str(value).strip()
        if text == "":
            return None
        return float(text)
    except ValueError:
        return None


def chooseColumn(headers, preferred, aliases):
    for name in [preferred] + aliases:
        if name in headers:
            return name
    lowerMap = {header.lower(): header for header in headers}
    for name in [preferred] + aliases:
        if name.lower() in lowerMap:
            return lowerMap[name.lower()]
    return None


def paired(rows, xColumn, yColumn):
    points = []
    for row in rows:
        x = toFloat(row.get(xColumn))
        y = toFloat(row.get(yColumn))
        if x is not None and y is not None:
            points.append((x, y))
    points.sort(key=lambda item: item[0])
    return points


def filterRowsByX(rows, xColumn, minX):
    if minX is None:
        return rows
    filtered = []
    for row in rows:
        x = toFloat(row.get(xColumn))
        if x is not None and x >= minX:
            filtered.append(row)
    return filtered


def addMultiAxis(host, xValues, yValues, label, color, axisIndex):
    if axisIndex == 0:
        axis = host
    else:
        axis = host.twinx()
        axis.spines["right"].set_position(("axes", 1 + 0.12 * (axisIndex - 1)))
        axis.spines["right"].set_visible(True)
    axis.plot(xValues, yValues, color=color, linewidth=1.3, marker="o", markersize=2.5, label=label)
    axis.set_ylabel(label, color=color)
    axis.tick_params(axis="y", colors=color)
    return axis


def writeInterpolated(rows, xColumn, yColumns, points, output):
    if not points or not output:
        return None
    sourceX = [toFloat(row.get(xColumn)) for row in rows]
    outputRows = []
    for point in points:
        item = {xColumn: point}
        for yColumn in yColumns:
            pairs = paired(rows, xColumn, yColumn)
            item[yColumn] = interpolate(pairs, point)
        outputRows.append(item)
    with Path(output).open("w", encoding="utf-8-sig", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=[xColumn] + yColumns)
        writer.writeheader()
        writer.writerows(outputRows)
    return str(Path(output).resolve())


def interpolate(pairs, target):
    if not pairs:
        return None
    if target <= pairs[0][0]:
        return pairs[0][1]
    if target >= pairs[-1][0]:
        return pairs[-1][1]
    for index in range(1, len(pairs)):
        x0, y0 = pairs[index - 1]
        x1, y1 = pairs[index]
        if x0 <= target <= x1 and x1 != x0:
            ratio = (target - x0) / (x1 - x0)
            return y0 + ratio * (y1 - y0)
    return None


def main():
    parser = argparse.ArgumentParser(description="Plot converted parametric scan performance with true multiple y-axes.")
    parser.add_argument("csvFile", help="CSV generated by convert_prmresult.py.")
    parser.add_argument("--output", required=True, help="Output PNG path.")
    parser.add_argument("--x-axis", default="Tmech", help="Default x-axis is Tmech for torque-axis measured reports.")
    parser.add_argument("--y-columns", default="Pin,Pmech,eff,Udc,Idc,rspeed", help="Comma-separated y columns.")
    parser.add_argument("--min-x", type=float, default=0.0, help="Minimum x value to keep. Default filters out negative mechanical torque.")
    parser.add_argument("--interpolate-at", default="", help="Comma-separated x values for interpolation.")
    parser.add_argument("--interpolation-output", help="Optional CSV for interpolated values.")
    parser.add_argument("--evidence-output", help="Optional evidence JSON output path.")
    args = parser.parse_args()

    try:
        plt = requireMatplotlib()
    except ImportError as error:
        result = {"warnings": [f"matplotlib is required for plotting: {error}"], "figures": []}
        print(json.dumps(result, ensure_ascii=False, indent=2))
        return

    rows, encoding = readCsv(args.csvFile)
    headers = rows[0].keys() if rows else []
    xColumn = chooseColumn(headers, args.x_axis, ["Tmech", "Tem", "torque", "输出转矩", "机械转矩"])
    if not xColumn:
        raise ValueError(f"Could not find x-axis column: {args.x_axis}")
    rows = filterRowsByX(rows, xColumn, args.min_x)
    if not rows:
        raise ValueError(f"No rows remain after filtering {xColumn} >= {args.min_x}.")

    requestedY = [item.strip() for item in args.y_columns.split(",") if item.strip()]
    yColumns = [chooseColumn(headers, item, [item]) for item in requestedY]
    yColumns = [item for item in yColumns if item and item != xColumn]
    if not yColumns:
        raise ValueError("No y columns found for parametric performance plot.")

    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    colors = ["#1f77b4", "#d62728", "#2ca02c", "#9467bd", "#ff7f0e", "#17becf"]
    fig, host = plt.subplots(figsize=(9, 5.2), dpi=150)
    axes = []
    plotted = []
    warnings = []
    for yColumn in yColumns:
        points = paired(rows, xColumn, yColumn)
        if len(points) < 2:
            warnings.append(f"Not enough points for {yColumn}")
            continue
        xs = [point[0] for point in points]
        ys = [point[1] for point in points]
        axis = addMultiAxis(host, xs, ys, yColumn, colors[len(plotted) % len(colors)], len(plotted))
        axes.append(axis)
        plotted.append(yColumn)

    host.set_xlabel(xColumn)
    host.set_xlim(left=args.min_x)
    host.set_title("Parametric Scan Performance")
    host.grid(True, alpha=0.3)
    lines = []
    labels = []
    for axis in axes:
        axisLines, axisLabels = axis.get_legend_handles_labels()
        lines.extend(axisLines)
        labels.extend(axisLabels)
    if lines:
        host.legend(lines, labels, loc="best", fontsize=8)
    fig.subplots_adjust(right=0.62)
    fig.savefig(output, bbox_inches="tight")
    plt.close(fig)

    interpolationOutput = None
    if args.interpolate_at:
        points = [float(item.strip()) for item in args.interpolate_at.split(",") if item.strip()]
        interpolationOutput = writeInterpolated(rows, xColumn, plotted, points, args.interpolation_output)

    record = {
        "evidenceId": f"figure-parametric-{Path(args.csvFile).stem}",
        "sourceFile": str(Path(args.csvFile).resolve()),
        "relativePath": str(Path(args.csvFile).name),
        "sourceRole": "figure",
        "generatedFile": str(output.resolve()),
        "figureKind": "parametricPerformance",
        "metricNames": plotted,
        "extractionMethod": "plot_parametric_performance.py",
        "confidence": 0.75,
        "notes": f"encoding={encoding}; x={xColumn}; minX={args.min_x}; true multi-axis; interpolationOutput={interpolationOutput or ''}"
    }
    result = {"warnings": warnings, "figures": [record], "interpolationOutput": interpolationOutput}
    outputText = json.dumps(result, ensure_ascii=False, indent=2)
    if args.evidence_output:
        Path(args.evidence_output).write_text(outputText, encoding="utf-8")
    print(outputText)


if __name__ == "__main__":
    main()
